[build-system]
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "sat-utils"
version = "1.0.1"
authors = [
  { name="Ryan Semmler", email="rsemmle@ncsu.edu" },
]
description = "Contains a collection of shared utility functions"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.6"
dependencies = [ "fastapi", "jwt", "slack-sdk" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.entry-points."sat_utils.auth_checker"]
"sat_utils.auth_checker" = "sat_utils.auth_checker:AuthChecker"
"sat_utils.slack" = "sat_utils.slack:Slack"

[project.urls]
"Homepage" = "https://github.ncsu.edu/SAT/sat-utils"

[tool.flit.module]
name = "sat_utils"